name = "Useless Catch";
description = "Catch clause should handle the exception with some work. 

Among the task of a catch clause : log the exception, clean any mess that was introduced, fail graciously. 

<?php

function foo($a) {
    try {
        $b = doSomething($a);
    } catch (Throwable $e) {
        // No log of the exception : no one knows it happened.
        
        // return immediately ? 
        return false;
    }
    
    $b->complete();
    
    return $b;
}

?>

See also `Exceptions <http://php.net/manual/en/language.exceptions.php>`_.
";
clearphp = "";
severity = "S_MINOR";
timetofix = "T_SLOW";
exakatSince = "1.1.4";